gem 'rspec'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new(:spec) do |t|
  t.fail_on_error = false
  t.rspec_opts = []
  t.pattern = ARGV[1] || "spec/*_spec.rb"
end

begin
  require 'jasmine'
  load 'jasmine/tasks/jasmine.rake'
rescue LoadError
  task :jasmine do
    abort "Jasmine is not available. In order to run jasmine, you must: (sudo) gem install jasmine"
  end
end

task :py do
  puts 'Merge Sort Test -'
  `python -m unittest spec.merge_sort_test`
  puts 'Quick Sort Test -'
  `python -m unittest spec.quick_sort_test`
end

task default: :spec
